# FAÇA UM PROGRAMA QUE POSSUA UM VETOR DENOMINADO "A" QUE ARMAZENE 6 NÚMEROS INTEIROS. 
# O PROGRAMA DEVE EXECUTAR OS SEGUINTES PASSOS:
# - ATRIBUA OS VALORES A ESSE VETOR: 1,0,5,-2,-5,-7
# - ARMAZENE EM UMA VARIAVEL A SOMA ENTRE OS VALORES NAS POSIÇÕES A[0],A[1] E A[5]
# - MODIFIQUE O VETOR NA POSIÇÃO 4, ATRIBUINDO O VALOR 100
# - MOSTRE NA TELA CADA VALOR DO VETOR "A", UM EM CADA LINHA

a = [1,0,5,-2,-5,-7]

soma = [a[0]+a[1]+(a[5])]
a [4] = 100

for i in a:
    print (i)

print (soma)